Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

AllCops:
  Exclude:
    - 'bin/**/*'
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
